import mongoose from 'mongoose';
import crypto from 'crypto';

const meetingSchema = new mongoose.Schema(
  {
    roomCode: {
      type: String,
      unique: true,
      required: true,
      index: true,
    },
    title: {
      type: String,
      default: 'Untitled Meeting',
      trim: true,
      maxlength: 100,
    },
    hostId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    status: {
      type: String,
      enum: ['waiting', 'active', 'ended'],
      default: 'waiting',
    },
    participants: [
      {
        userId: {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'User',
        },
        displayName: String,
        targetLanguage: {
          type: String,
          default: 'en',
        },
        socketId: String,
        joinedAt: {
          type: Date,
          default: Date.now,
        },
        isActive: {
          type: Boolean,
          default: true,
        },
      },
    ],
    endedAt: Date,

    // Post-meeting AI summary generated by Gemini Flash
    summary: {
      executiveSummary: { type: String, default: '' },
      keyTopics: [{ type: String }],
      actionItems: [{ type: String }],
      generatedAt: { type: Date },
    },
  },
  {
    timestamps: true,
  }
);

// Generate a unique room code (e.g., "abc-defg-hij")
meetingSchema.statics.generateRoomCode = function () {
  const chars = 'abcdefghijklmnopqrstuvwxyz';
  const seg1 = Array.from({ length: 3 }, () => chars[Math.floor(Math.random() * chars.length)]).join('');
  const seg2 = Array.from({ length: 4 }, () => chars[Math.floor(Math.random() * chars.length)]).join('');
  const seg3 = Array.from({ length: 3 }, () => chars[Math.floor(Math.random() * chars.length)]).join('');
  return `${seg1}-${seg2}-${seg3}`;
};

// Get active participants (guaranteed unique by userId)
meetingSchema.methods.getActiveParticipants = function () {
  const seen = new Set();
  const active = [];
  for (const p of this.participants) {
    if (p.isActive) {
      const uid = p.userId ? p.userId.toString() : null;
      if (uid && !seen.has(uid)) {
        seen.add(uid);
        active.push(p);
      }
    }
  }
  return active;
};


export default mongoose.model('Meeting', meetingSchema);
